 CLASS zcl_923_r_travel_test DEFINITION
  PUBLIC FINAL
  CREATE PUBLIC
  FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS zcl_923_r_travel_test IMPLEMENTATION.
 ENDCLASS.
